### ISSUE TITLE
Pending common a11y issues

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/area-model-common#154]
I'll add any common issues here that need to be resolved before the 1.1 release.

- [x] https://github.com/phetsims/sun/issues/356 (readout for NumberPicker)
- [x] https://github.com/phetsims/sun/issues/357 (name/description for NumberPicker
- [ ] https://github.com/phetsims/sun/issues/358 (AccessibleSlider options)
- [ ] https://github.com/phetsims/sun/issues/359 (AccordionBox a11y design)
- [ ] https://github.com/phetsims/sun/issues/361 (RadioButtonGroup description location)
- [ ] https://github.com/phetsims/a11y-research/issues/104 (Multi-screen PDOM)
- [ ] https://github.com/phetsims/sun/issues/368 (AccessibleSlider mutable decimal places)
- [ ] https://github.com/phetsims/scenery-phet/issues/367 (Mutable KeyboardDragListener)
- [ ] https://github.com/phetsims/joist/issues/496 (Home Screen work)
- [ ] #164 (number picker descriptions for area-model)
